language: ruby
rvm:
- 2.3.4
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libxml2-dev nodejs
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- cp config/config.yml.travis config/config.yml
script:
- bin/rails db:migrate RAILS_ENV=test
- bin/rails spec
notifications:
  slack:
    secure: EpFueQWJ4RlndF8qI609THj19U9h0W8bC+uNoX8sJGhLd3M5ZQQKwusgX0m+SwGsLWKXCoVgp+bq+Segz+nbePNkwEgwklrAUQ/4L2xVgvr5PuQlnAAoEPIkhDNUr9hYqn32CV6QeQfM8F0DrKLMtx/4NyQNTR/jcS8AUrgO8XgTWpmdmCaEp0K1Iaw90e1V/Bi55Rhk5dD98fVSCnTKhBAoRv1yJsEqq6ndocOE1Xn8G38ElP4Dcb+LTIU/j8XXnFpzcjXAEE6HY68EbNW4nWLeW/P+6D4m/L5/5eJWnZPJQvwyxAgrzCabIi5m4WrSUH1GGfOqYOks91ablUd2/9Feevb5QcMDwJP28zV2o1QUwnW9JhDSWR/qEjIrUFtFFS6q7cmaEyEUMDDjeroIUEXe66c9ZqmlJnPFkyuwYlj3VN4ImLeMFG4YPs+4if3mn+RPfmyJGbFRfXVbMEVuFtgC9hGlE/uEbGDEgZd1KzS1m+9wx+9tfjuasYdiu/xe/9IcsOupYqF8H4JSZdivgYDdH9/qxSPMVGWKCG1ChWfhPvgov2dqHdB44mHD1jEDo5CXOkwqoPfoCLB5vay5n6keqGN5dyyJfAKlAZqCHHbBqYKCuU8vXopYDnIrhnb7lmIt5PSE/+uVRzMEfYkqsXb9D43u11F4DojdM+89oVk=
