# frozen_string_literal: true

# OmniAuth 2.0+ configuration
# Reference: https://github.com/omniauth/omniauth/wiki/Resolving-CVE-2015-9284

# Only allow POST requests to initiate OAuth (security best practice)
OmniAuth.config.allowed_request_methods = [:post]

# Disable OmniAuth's built-in CSRF protection since Rails already provides CSRF protection
# via the authenticity_token in forms generated by button_to
# This is safe because:
# 1. We're using button_to which generates POST forms with Rails CSRF tokens
# 2. Rails ApplicationController has protect_from_forgery enabled by default
OmniAuth.config.request_validation_phase = nil
